### ISSUE TITLE
Misalignment of maximized titlebar. Visible in blue highlight of active tab and when hovering mouse over Min/Max/Close buttons

### ISSUE THREAD

**Issue by Rosmaninho** [conema/monterail-dark#8] opened 2018-08-27 10:38 UTC
![thunder](https://user-images.githubusercontent.com/42737369/44655481-2b15ea80-a9ed-11e8-8c40-880d230c1d02.png)
![thunderbird](https://user-images.githubusercontent.com/42737369/44655482-2bae8100-a9ed-11e8-987e-db8cf49e1e76.PNG)

Since you forked the Monterail theme from Paenglab I also commented in this bug in Bugzilla about the same issue that is present in your versions of the theme:

https://bugzilla.mozilla.org/show_bug.cgi?id=1325184

When Thunderbird is maximized in full screen, the tab bar cuts of the active tab highlight and the minimize, maximize and close buttons are also misaligned since when you hover with the mouse over them, the hit box is larger than the actual buttons..
It seems there's some minor misplacement in that case.

This is visible in Windows 10.

**Comment by conema** [comment] 2018-08-27 11:08
Thanks for your report!
I confirm the problem with the hover, but I can't reproduce the tab bar cut with Windows 10, it's very strange. 

Are you using Thunderbird 60.0 (stable, not beta)?
Do you have this problem only with the Monterail themes?
What screen resolution do you currently have?
Did you tried to reinstall thunderbird?

PS: are you the same user of the review?

**Comment by Rosmaninho** [comment] 2018-08-27 12:06
Yes, I'm the same user as in the review both in Monterail dark and Monterail Full Dark. :)

I only have this problem with the Monterail themes, but they're the only complete themes that I installed... All the other are hideous themes that look like they came from the early 00's.

My Thunderbird is from the release channel, so it should be the stable one.
This problem occurs both in my notebook original 1366x768 display and in my external 1080p displays.

The tab bar cut is just the blue highlight on top of the active tab that is much thinner. I think this happens because the entire bar is misaligned a couple of pixels to the top when fully maximized... 
Can't confirm this though.

Paenglab said he had a fix incoming but still didn't update the Monterail theme so don't know when it'll be fixed.

**Comment by conema** [comment] 2018-08-27 13:18
> The tab bar cut is just the blue highlight on top of the active tab that is much thinner. I think this happens because the entire bar is misaligned a couple of pixels to the top when fully maximized

But this is really strange, I'm testing in two Windows 10 environment and I can't reproduce this issue, even with the same resolution. I think that the problem could have something to do with compatibility between other addons and the theme. Do you have some other addon installed? Did you try to disable them temporarily?

> Paenglab said he had a fix incoming but still didn't update the Monterail theme so don't know when it'll be fixed.

For what I understood, Paenglab didn't found a solution for the problem, because he too can't reproduce the problem with the tab, he only resolved the hover bug.

If you have some spare time, I think that we can resolve this issue, but I have the *omen* that this does not have to do directly with the theme.

**Comment by conema** [comment] 2018-08-29 09:28
> I think fixing one will fix both.
But it seems strange to me, the hover bug is present, but I really can't reproduce the tab-line problem that you are having and I need to know the cause in order to do a fix. I am afraid that it may be a problem related to some local configuration.

When you can, I'd like to know:
1) Do you have some other addon installed? Did you try to disable them temporarily?
2) Did you try to do a fresh thunderbird installation?
3) May you send me other two screenshot, one maximized without hover and one maximized with hover and with tools menu opened (it can be opened with alt key on the keyboard)?

However, I'll resolve the hover problem, but I think that this fix will not resolve the other issue.


> Nice work with resolving the compatibility issues with the other Monterail themes. 

I'm happy to hear that! Remember to update your review as soon as you can for update the other users that the problem is fixed.

**Comment by Rosmaninho** [comment] 2018-09-03 08:49
1 - Yes, I have other add-ons installed. Checkbox Column, CompactHeader, Exquilla, Lightning, Provider for Google Calendar, Send Later, Send Later Button, and TbSync. Tried to disable all of them and still have same issue.

2 - Yes. Did not fix the problem.

3 - Here's the image.
![imagem3](https://user-images.githubusercontent.com/42737369/44976944-9831fe80-af5e-11e8-89e2-d61b1b337bed.png)

**Comment by conema** [comment] 2018-09-03 21:28
I'm so sorry that that took so long, I understood what you was referring to only today!
However, I made a fix and I'll happy if you can test it! Try it and let me know if there are any problem.
(You should rename the zip file "chrome.zip" to "chrome.xpi" and install it like a normal theme - more info in the theme FAQ)

[chrome.zip](https://github.com/conema/monterail-dark/files/2346562/chrome.zip)

**Comment by Rosmaninho** [comment] 2018-09-03 22:31
The black line is because I did some quick Print Screens from dual monitors. :)

Thunderbird was on the lower resolution display.

**Comment by Rosmaninho** [comment] 2018-09-03 22:35
Woohoo! You managed to fix it! :D

**Comment by Rosmaninho** [comment] 2018-09-04 07:57
i'm extremely grateful. this way my OCD stops triggering. :P

**Comment by conema** [comment] 2018-09-04 13:00
I'm happy to hear this! I really misunderstood the issue all the time! I'll close this and I'll update the theme soon.

**Closed by conema** 2018-09-04 13:00 UTC
Labels: bug

**Comment by Rosmaninho** [comment] 2018-09-05 08:20
So, just one question... Since I updated Monterail Dark via the zip file you sent me. Do I have to uninstall it and reinstall the theme after it is updated in the store?

**Comment by conema** [comment] 2018-09-05 10:33
I don't know how updates works with Thunderbird Addon I'll comment in this issue to let you know when the new update will been out. Don't worry!

**Comment by conema** [comment] 2018-09-05 20:57
Okay, I pushed this and the lighting fix on the addons site, we need to wait for approval (1/2 day max).

**Comment by Rosmaninho** [comment] 2018-09-07 18:04
Holy crap, the changes in the calendar and task tab are amazing!!!
