### ISSUE TITLE
thunderbird 68

### ISSUE THREAD

**Issue by jettrich** [conema/monterail-dark#31] opened 2019-08-30 09:37 UTC
I've updated to thunderbird 68, thus the themes (I use MONTERAIL DARK) are no longer working. Unfortunately I cannot find any "manual/howto" which guides me in creating a theme with webExtensions 8what seems to be standard now) :/ thus, can you point me to some resource, which would help me in transferring you great theme in the new format? or did you already started doing this?

Cheers
Jörg

**Comment by conema** [comment] 2019-08-30 11:33
Hi Jörg,
The only howto that I have found is [this](https://developer.thunderbird.net/add-ons/tutorials/web-extension-themes). I'd like to re-create this theme with webExtension, but for what I understood, full themes (and so, the monterail themes) are no more supported because the new APIs are very limited, for this reason a lot of themes are giving up the support of the new TB version. 
At the moment I think that the most clever thing it is to wait and see what happens with themes support. Update me if you find something new.

**Comment by shiro** [comment] 2019-10-07 12:32
Following the discussion here: https://bugzilla.mozilla.org/show_bug.cgi?id=1325184#c123
the official theme is now packages as a regular extension and does work on TB 68 (tested just now).

Would be great if something like that was possible with the dark theme as well.

Apparently the WebExtension API does not support a lot of stuff, and removing features from the theme would be highly detrimental to the experience.

**Comment by conema** [comment] 2019-10-07 16:18
Thanks @shiro, this is really useful to know!

**Comment by srgmro-33** [comment] 2019-11-11 14:20
I used the last release from monterail-2.0 and it works perfectly for me under ubuntu 18.04. It installs as an extension. Hope that this could help you.
SM

**Comment by frumble** [comment] 2019-11-11 18:43
@srgmro-33 Where did you get this? I can just find a version 1.1.

**Comment by srgmro-33** [comment] 2019-11-11 18:53
Here it is
[monterail-2.0-tb.xpi.txt](https://github.com/conema/monterail-dark/files/3832793/monterail-2.0-tb.xpi.txt)
Remove txt extension for use

**Comment by frumble** [comment] 2019-11-11 20:01
I have certain reservation for installing a undocumented XPI file… Where did you even find this? The project Github page does not mention it and in the zipped folder, the youngest filestamps are from July. That’s somehow unlogical considering Thunderbird 68 came in August and the outcry over lost themes (especially Monterail) was big.

**Comment by srgmro-33** [comment] 2019-11-11 20:04
I get it here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1325184#c123
It comes from the author of the author of Monterail dark

**Comment by srgmro-33** [comment] 2019-11-11 20:06
See above the comment of shiro

**Comment by conema** [comment] 2019-11-11 20:42
Hi guys, I'm a little busy these last months but I really want to make this theme compatible with the last TB (the default theme is killing me slowly). The idea is to look at the work done by Paenglab and convert this theme by the end of November, if it's possible. In the meantime, if somebody want to help me, he is free to open a PR. I will update this thread as soon as possible

**Comment by srgmro-33** [comment] 2019-11-11 21:00
What actually works for me  is a combination of the Numix blue theme and the monterail -TB 2.0
Perhaps a way to reach the goal is to design a specific theme and to add an extension as suggest by Richard Marti (Paenglab). I am unable to do such a job.
Sorry and many thanks for your interest.

**Comment by conema** [comment] 2019-11-12 18:32
Hi again, I just made a beta version that y'all can use until I release the stable one, it should be like the theme for the old thunderbird. The .zip archive should be renamed in .xpi and installed like a normal addon.

If someone find something bad, please report it, so I can resolve it. At the moment the only problem is that the arrows of the folderTree (the element with the folders, on the left) as a black arrows instead of a white ones)

[monterail-dark-2-beta.zip](https://github.com/conema/monterail-dark/files/3837625/monterail-dark-2-beta.zip)

**Comment by rnc** [comment] 2019-11-12 19:01
Thats brilliant!! Nice one :+1:  :1st_place_medal: 

Couple of comments:
1. The font on the left hand side, especially with the bolded folders is rather large.

Compare
![Screenshot_20191112_185852](https://user-images.githubusercontent.com/1169793/68701376-8f838200-057e-11ea-8111-f95417696704.png)
to
![Screenshot_20191112_190031](https://user-images.githubusercontent.com/1169793/68701469-bd68c680-057e-11ea-85b0-350122ab2106.png)

2. The rows seem to be rather widely spaced. I don't know if its possible to change that?

![Screenshot_20191112_185200](https://user-images.githubusercontent.com/1169793/68700891-9e1d6980-057d-11ea-8950-4d00e4e20d3e.png)

**Comment by conema** [comment] 2019-11-12 19:16
> The font on the left hand side, especially with the bolded folders is rather large.

May you make a full height screenshoot of the folders?


> The rows seem to be rather widely spaced. I don't know if its possible to change that?

If you mean widely spaced in height, look [here](https://github.com/conema/monterail-dark/issues/13) (the correct directory of the 3rd point is /skin/)

**Comment by srgmro-33** [comment] 2019-11-12 21:27
Nice work. Installation on ubuntu 18.04 starting from default theme of thunderbird.
See added screen
![Screenshot_20191112_222224](https://user-images.githubusercontent.com/56195634/68712251-a2587f80-059b-11ea-89ce-4a433932d82d.jpeg)

**Comment by rnc** [comment] 2019-11-12 22:27
Ok changing both 
```
   --message-list-row-height: 40px; 
     --folder-tree-row-height: 25px; 
```
to
```
    --message-list-row-height: 1.5rem;
    --folder-tree-row-height: 1.5rem;
```
as per your linked suggestion works nicely ; see below:

![Screenshot_20191112_222614](https://user-images.githubusercontent.com/1169793/68716201-9c629e80-059b-11ea-8c7e-ddc578bfc6ec.png)

**Comment by srgmro-33** [comment] 2019-11-13 06:09
I checked various combinations of monterail with some themes.
Don't display with convenient color fonts with light theme from thunderbird.
Pleasant look with Numix blue. I modified Numix blue to get a orange line.
See added file
[numix_orange-1.2-tb.xpi.txt](https://github.com/conema/monterail-dark/files/3839636/numix_orange-1.2-tb.xpi.txt)

**Comment by rnc** [comment] 2019-11-13 07:03
> > The font on the left hand side, especially with the bolded folders is rather large.
> 
> May you make a full height screenshoot of the folders?
> 

I have made a larger screenshot. 
![Screenshot_20191113_065259](https://user-images.githubusercontent.com/1169793/68740553-3ac62280-05e3-11ea-805d-c7f1b1947010.png)

Then I tried commenting out the font instructions in root.css:
![Screenshot_20191113_065943](https://user-images.githubusercontent.com/1169793/68740565-44e82100-05e3-11ea-97e4-f53f0122d0e8.png)

I think that illustrates the difference - it seems my default font must be 'smaller' so the bold is less, er, 'intrusive' on the eye. Apologies for the slightly vague description not sure how best to phrase it.

Question: what does do?
```
  font-family: var(--default-font);
```
For me, with those changes, it looks great!

**Comment by conema** [comment] 2019-11-13 07:15
@rnc
> Could (long term!!) this be made an option perhaps?

I hope... I'm going to see for how long legacy extensions are going to work with the new TB version.

> Question: what does do?

There was a bug on that version of the theme, it was using the OS font and not the font that I specified, I fixed it. See if this new version works good for you, maybe I will add an option like for the height of the threads.

@srgmro-33 

> I checked various combinations of monterail with some themes.
Don't display with convenient color fonts with light theme from thunderbird.

I read that too on the Monterail theme, I think that "normal" themes are overwriting the changes done by themes. For now we should use the default theme or, however, a compatible theme like numix.




**New version**, I'll upload it as soon as possible to the thunderbird addons page:
[monterail-dark-2.0.zip](https://github.com/conema/monterail-dark/files/3839812/monterail-dark-2.0.zip)

**Comment by rnc** [comment] 2019-11-13 10:19
@conema  That fix looks *much* better. That has solved the font problems for me. I have tweaked the height of the threads again.

**Comment by daxid** [comment] 2019-11-13 11:56
Hi, @conema . Thanks for your work.
The new 2.0 version breaks the search result page. The 2.0-beta was OK on this regard.

PS : To people complaining about this not working with dark themes, you can always edit colours in the root.css file. I managed to have a nearly perfect rendering matching breeze-dark colours. Only remaining colour problems are the headers in the thread panel and some stuff in the window to edit a new message.

**Comment by frumble** [comment] 2019-11-13 19:27
Huh, the new 2.0 makes read mails basically invisible for me.
![Screenshot_20191113_202539](https://user-images.githubusercontent.com/1595877/68796914-e6a75680-0653-11ea-87a3-150337e8b193.png)

**Comment by rnc** [comment] 2019-11-13 19:28
@frumble What desktop theme, operating system etc are you using? Its perfect for me using Fedora 31, KDE Plasma spin and Breeze Dark theme.

**Comment by frumble** [comment] 2019-11-13 19:30
@rnc Plasma 5.17.3 on Arch, standard Breeze theme.

**Comment by rnc** [comment] 2019-11-13 19:32
@daxid @conema I can confirm also the search page doesn't look correct for me. Do you want a screenshot ? 

Also, the mail compose window colour looks _slightly_ different - according to kcolorchooser, the mail window is using `#3c3b37` but the main thunderbird window is using `#494844`.

**Comment by rnc** [comment] 2019-11-13 19:32
@frumble I wonder if its the interaction with breeze standard - have you tried breeze dark ?

**Comment by frumble** [comment] 2019-11-13 19:39
@rnc No difference with Breeze Dark for me.

**Comment by conema** [comment] 2019-11-13 22:21
@daxid 
> The new 2.0 version breaks the search result page. The 2.0-beta was OK on this regard.

Fixed, ty.

@rmc
> Also, the mail compose window colour looks slightly different - according to kcolorchooser, the mail window is using #3c3b37 but the main thunderbird window is using #494844.

The window change color if it's active or inactive, the active is darker. Is this the case?

@frumble 
Does only the message list appear with the wrong color? Does it change using the default TB theme?

New version with search fixed:
[monterail-2.0-tb.zip](https://github.com/conema/monterail-dark/files/3843697/monterail-2.0-tb.zip)

**Comment by frumble** [comment] 2019-11-14 00:40
@conema Yes, only the message list. No problem using the two default Thunderbird themes.

**Comment by rnc** [comment] 2019-11-14 06:51
@conema  Ah. I switched to using gpick as it has focus follows mouse mode and this revealed that you are correct there is an active/inactive different _but_ there is a slight issue - the compose window doesn't _seem_ to switch to an inactive colour. It would be useful if someone else could verify this ?

**Comment by conema** [comment] 2019-11-14 07:59
@rnc 
> the compose window doesn't seem to switch to an inactive colour

You were right, it wasn't switching, fixed.

@frumble 
> Yes, only the message list. No problem using the two default Thunderbird themes.

Any problem using monterail dark + the default one (the first of the list on the screen)? Could you test this new update?

![immagine](https://user-images.githubusercontent.com/12801153/68836699-3b31ec80-06bb-11ea-961d-2ccc4322c10b.png)


New version with active/inactive fix for compose and fix for frumble (maybe):
[monterail-dark-2.0.zip](https://github.com/conema/monterail-dark/files/3845259/monterail-dark-2.0.zip)

**Comment by rnc** [comment] 2019-11-14 11:09
@conema Thats great, thats fixed that one ..... but sorry but found another slight issue ;-) For the main window, whether active or inactive, the menu bar text is in white - however the compose window appears to have black text  *except* if I hover over the menu it turns white. So I think its missing a selector?

**Comment by conema** [comment] 2019-11-14 13:13
@rnc That's strange. Can it be fault of the theme that you are using?

However, try this and let me know if it fix it:
[monterail-dark-2.0.zip](https://github.com/conema/monterail-dark/files/3846615/monterail-dark-2.0.zip)

**Comment by rnc** [comment] 2019-11-14 14:03
Woo! PERFECT!!! :1st_place_medal:

**Comment by dartcafe** [comment] 2019-11-14 15:05
Colors in Folder list and in mails list are still not good. Tried latest zip file. (68.2.2 fresh profile without add-ons)

The 5th mail is opened in all screenshots. 

Light theme
![grafik](https://user-images.githubusercontent.com/26707476/68868772-6129b200-06f8-11ea-8f82-07e383bc49d4.png)
Standard theme
![grafik](https://user-images.githubusercontent.com/26707476/68868806-6e46a100-06f8-11ea-858b-0dc499cba91b.png)
Dark theme
![grafik](https://user-images.githubusercontent.com/26707476/68868851-84546180-06f8-11ea-825c-eba03baa6668.png)

**Comment by conema** [comment] 2019-11-14 19:04
@dartcafe @frumble This update should fix the problems with colors
[monterail-dark-2.0.zip](https://github.com/conema/monterail-dark/files/3848206/monterail-dark-2.0.zip)

**Comment by conema** [comment] 2019-11-18 20:01
Here the download from the addons website: https://addons.thunderbird.net/it/thunderbird/addon/monterail-dark-2-0-for-tb-68/

I'm closing this issue, if you find any problem, open a new one.

**Closed by conema** 2019-11-18 20:01 UTC
Labels: >68.x, bug

**Comment by frumble** [comment] 2020-02-02 20:21
Found the cause for my nearly unreadable white lists before: I’ve applied this add-on on top of the dark standard theme. Applied on top of the default theme, everything is readable, including the event list in calender, which was still affected even after the November update. Maybe just write a hint on the Add-On page to only apply this on top of the default-non-dark-non-light theme.

**Comment by conema** [comment] 2020-02-03 12:51
> 
> 
> Found the cause for my nearly unreadable white lists before: I’ve applied this add-on on top of the dark standard theme. Applied on top of the default theme, everything is readable, including the event list in calender, which was still affected even after the November update. Maybe just write a hint on the Add-On page to only apply this on top of the default-non-dark-non-light theme.

This should be resolve with version 2.1, are you using that?

**Comment by frumble** [comment] 2020-03-21 20:12
Yes, 2.1 and still seeing this bug.
